name: Marp Workflow

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Build Marp slide deck
        run: CHROME_PATH=$(npx -y @puppeteer/browsers@latest install chrome@stable --path $(realpath ./tmp) | awk '{print $2}') npm run build:all
      
      - name: Update username config.
        run: git config --local user.name "github-actions[bot]"
        
      - name: Update the user email config. 
        run: git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stage changed files.
        run: git add .

      - name: Commit changed files.
        run: git commit -m "Auto updating presentation files."

      - name: Update remote origin url.
        run: git remote set-url origin https://hashbangcode:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Push code to master
        run: git push origin master